### ISSUE TITLE
AuthTokenController in app/controllers

### ISSUE THREAD

**Issue by fmendoza** [tappleby/laravel-auth-token#5]
Hi, how can i get this working?

**Comment by eneks** [comment]
Thanks @AMHOL for your info, I had problems to bind your code and I solved it adding $events:

        $this->app->bind('AuthController', function ($app) {
            $driver = $app['tappleby.auth.token']->driver();
            $credsFormatter = $app['config']->get('laravel-auth-token::format_credentials', null);
            $events = $app['events'];
            return new \AuthController($driver, $credsFormatter,$events);
        });
