### ISSUE TITLE
Auth::user() returning NULL

### ISSUE THREAD

**Issue by publicFunction** [tappleby/laravel-auth-token#53]
Hi,

I have just started using this package and I like it.

I have, however stumbled into a small issue. On my local development copy everything works fine, but on my staging copy when I call \Auth::user(). I get a null result.

Both versions are running php 5.5+ and laravel 4.2.11.

The issue on staging appears to be that the user is not being logged in correctly and as I cant repeat the issue locallly, its hard to debug the issue.

**Comment by tappleby** [comment]
@publicFunction Closing for now, reopen if still an issue.

**Comment by joshuaxd** [comment]
Hey fella. I am seeing this again on another project. Setup with a diff environment on the same machine. This environment is called testing and when I dump out Auth::user() it returns null to any environment that is not local or live. It all works well for either of these 2 env names, but when you attempt to use testing or possibly a 3rd it fails.

**Comment by publicFunction** [comment]
Hey fella. I am seeing this again on another project. Setup with a diff environment on the same machine. This environment is called testing and when I dump out Auth::user() it returns null to any environment that is not local or live. It all works well for either of these 2 env names, but when you attempt to use testing or possibly a 3rd it fails.
